# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Step to check out the code
    - name: Set up Python
      uses: actions/setup-python@v2 # Step to set up Python on Window
      with:
        python-version: '3.x' # Specify the Python version (e.g., 3.8, 3.9)

    - name: Install dependencies  # Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask flake8 pytest

    - name: Lint with Flake8
      run: flake8 myenv/app.py

    - name: Run unit tests
      run: python myenv/test_app.py
